/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-10T04:49:16.681803072-03:00[America/Araguaina]
 * <br>
*  The generated test suite contains 33 tests
 * <br>
*  Covered targets: 204
 * <br>
*  Used time: 1h 0m 2s
 * <br>
*  Needed budget for current results: 79%
 * <br>
*  
*/
public class EvoMaster_Test {

    
    private static String baseUrlOfSut = "http://localhost:8080";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/products
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_0_getOnProductsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. GET on path '/products' defines a response schema but no response body found.
        given().accept("application/json")
                .get(baseUrlOfSut + "/products")
                .then()
                .statusCode(200)
                .assertThat()
                ; // the response payload was too large, above the threshold of 1000000 bytes. No assertion on it is therefore generated.
    }
    
    
    /**
    * Calls:
    * (500) GET:/products/{productName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 1 example:
    *   (-) PATH: productName -> Smartwatch Series 7
    */
    @Test(timeout = 60000)
    public void test_1_getOnProductShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .get(baseUrlOfSut + "/products/Smartwatch%20Series%207")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) POST:/products/{productName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 1 example:
    *   (-) PATH: productName -> Wireless Mouse
    */
    @Test(timeout = 60000)
    public void test_2_postOnProductShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .post(baseUrlOfSut + "/products/Wireless%20Mouse")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/products/{productName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 1 example:
    *   (-) PATH: productName -> Smartwatch Series 9
    */
    @Test(timeout = 60000)
    public void test_3_deleteOnProductShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/Smartwatch%20Series%209")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (201) POST:/products/{productName}
    * 2 - (200) GET:/products/{productName}
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_4_getOnProductReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        given().accept("*/*")
                .post(baseUrlOfSut + "/products/gNh")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        
        given().accept("application/json")
                .get(baseUrlOfSut + "/products/gNh")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("gNh"))
                .body("'features'.size()", equalTo(0))
                .body("'constraints'.size()", equalTo(0));
        
        // Cleanup actions
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/gNh")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (201) POST:/products/{productName}
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_5_postOnProductReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        given().accept("*/*")
                .post(baseUrlOfSut + "/products/l")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Cleanup actions
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/l")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * 1 - (201) POST:/products/{productName}
    * 2 - (204) DELETE:/products/{productName}
    * Found 2 potential faults of type-code 101
    */
    @Test(timeout = 60000)
    public void test_6_deleteOnProductReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        given().accept("*/*")
                .post(baseUrlOfSut + "/products/R")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. DELETE on path '/products/{productName}' defines a response schema but no response body found.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/R")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) GET:/products/{productName}/features
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 1 example:
    *   (-) PATH: productName -> AeroBook-Pro-15
    */
    @Test(timeout = 60000)
    public void test_7_getOnProductFeaturesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .get(baseUrlOfSut + "/products/AeroBook-Pro-15/features")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (200) GET:/products/{productName}/configurations
    * Using 1 example:
    *   (-) PATH: productName -> Laptop-Pro-X15
    */
    @Test(timeout = 60000)
    public void test_8_getOnConfigurationsReturnsEmptyList() throws Exception {
        
        given().accept("application/json")
                .get(baseUrlOfSut + "/products/Laptop-Pro-X15/configurations")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * 1 - (201) POST:/products/{productName}
    * 2 - (200) GET:/products/{productName}/features
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_9_getOnProductFeaturesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        ValidatableResponse res_0 = given().accept("*/*")
                .post(baseUrlOfSut + "/products/dsB7BzfU3Di9")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        String location_productName__2 = res_0.extract().header("location");
        assertTrue(isValidURIorEmpty(location_productName__2));
        
        given().accept("application/json")
                .get(resolveLocation(location_productName__2, baseUrlOfSut + "/products/dsB7BzfU3Di9/features"))
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
        
        // Cleanup actions
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/dsB7BzfU3Di9")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * 1 - (201) POST:/products/{productName}
    * 2 - (201) POST:/products/{productName}/configurations/{configurationName}
    * 3 - (204) GET:/products/{productName}/configurations/{configurationName}
    * Found 3 potential faults of type-code 101
    * Using 3 examples:
    *   (-) PATH: configurationName -> production-us-east
    *   (-) PATH: configurationName -> production-us-east-1
    *   (-) PATH: configurationName -> us-standard-wifi
    */
    @Test(timeout = 60000)
    public void test_10_getOnConfigurReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        ValidatableResponse res_0 = given().accept("*/*")
                .post(baseUrlOfSut + "/products/c5XXhxcPE9ypRdtb")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        String location_productName__2 = res_0.extract().header("location");
        assertTrue(isValidURIorEmpty(location_productName__2));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}/configurations/{configurationName}' defines a response schema but no response body found.
        given().accept("*/*")
                .post(resolveLocation(location_productName__2, baseUrlOfSut + "/products/c5XXhxcPE9ypRdtb/configurations/us-standard-wifi"))
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 204 not defined for path '/products/{productName}/configurations/{configurationName}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/products/c5XXhxcPE9ypRdtb/configurations/production-us-east-1")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Cleanup actions
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/c5XXhxcPE9ypRdtb")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
        given().accept("*/*")
                .delete(resolveLocation(location_productName__2, baseUrlOfSut + "/products/c5XXhxcPE9ypRdtb/configurations/production-us-east"))
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (201) POST:/products/{productName}
    * 2 - (201) POST:/products/{productName}/configurations/{configurationName}
    * 3 - (200) GET:/products/{productName}/configurations/{configurationName}
    * Found 2 potential faults of type-code 101
    */
    @Test(timeout = 60000)
    public void test_11_getOnConfigurReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        ValidatableResponse res_0 = given().accept("*/*")
                .post(baseUrlOfSut + "/products/m1_K5immkn")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        String location_productName__2 = res_0.extract().header("location");
        assertTrue(isValidURIorEmpty(location_productName__2));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}/configurations/{configurationName}' defines a response schema but no response body found.
        given().accept("*/*")
                .post(resolveLocation(location_productName__2, baseUrlOfSut + "/products/m1_K5immkn/configurations/ZXFRodXsHP"))
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        
        given().accept("application/json")
                .get(baseUrlOfSut + "/products/m1_K5immkn/configurations/ZXFRodXsHP")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("ZXFRodXsHP"))
                .body("'valid'", equalTo(true))
                .body("'activedFeatures'.size()", equalTo(0));
        
        // Cleanup actions
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/m1_K5immkn")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
        given().accept("*/*")
                .delete(resolveLocation(location_productName__2, baseUrlOfSut + "/products/m1_K5immkn/configurations/ZXFRodXsHP"))
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) POST:/products/{productName}/constraints/excludes
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 3 examples:
    *   (-) BODY -> CPU-i9-13900H
    *   (-) BODY -> Integrated-Graphics-Only
    *   (-) PATH: productName -> Laptop-Pro-15
    */
    @Test(timeout = 60000)
    public void test_12_postOnExcludesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .contentType("application/x-www-form-urlencoded")
                .body("sourceFeature=CPU-i9-13900H&excludedFeature=Integrated-Graphics-Only")
                .post(baseUrlOfSut + "/products/Laptop-Pro-15/constraints/excludes")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) POST:/products/{productName}/constraints/requires
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 3 examples:
    *   (-) BODY -> 128GB-ECC-RAM
    *   (-) BODY -> RAID-Controller-Card
    *   (-) PATH: productName -> Enterprise-Server-X1
    */
    @Test(timeout = 60000)
    public void test_13_postOnRequiresShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .contentType("application/x-www-form-urlencoded")
                .body("sourceFeature=RAID-Controller-Card&requiredFeature=128GB-ECC-RAM")
                .post(baseUrlOfSut + "/products/Enterprise-Server-X1/constraints/requires")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) POST:/products/{productName}/configurations/{configurationName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 2 examples:
    *   (-) PATH: configurationName -> us-standard-wifi
    *   (-) PATH: productName -> smart-thermostat-v3
    */
    @Test(timeout = 60000)
    public void test_14_postOnConfigurShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .post(baseUrlOfSut + "/products/smart-thermostat-v3/configurations/us-standard-wifi")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) POST:/products/{productName}/features/{featureName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 3 examples:
    *   (-) BODY -> Measures the oxygen saturation (SpO2) of your blood on demand.
    *   (-) PATH: featureName -> Blood Oxygen Sensor
    *   (-) PATH: productName -> Smartwatch Series 8
    */
    @Test(timeout = 60000)
    public void test_15_postOnProductFeaturShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .contentType("application/x-www-form-urlencoded")
                .body("description=Measures+the+oxygen+saturation+%28SpO2%29+of+your+blood+on+demand.")
                .post(baseUrlOfSut + "/products/Smartwatch%20Series%208/features/Blood%20Oxygen%20Sensor")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (201) POST:/products/{productName}
    * 2 - (201) POST:/products/{productName}/features/{featureName}
    * 3 - (200) PUT:/products/{productName}/features/{featureName}
    * Found 3 potential faults of type-code 101
    * Using 1 example:
    *   (-) BODY -> Measures the oxygen saturation (SpO2) of your blood on demand.
    */
    @Test(timeout = 60000)
    public void test_16_putOnFeaturReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        ValidatableResponse res_0 = given().accept("*/*")
                .post(baseUrlOfSut + "/products/hrjF")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        String location_productName__2 = res_0.extract().header("location");
        assertTrue(isValidURIorEmpty(location_productName__2));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}/features/{featureName}' defines a response schema but no response body found.
        given().accept("*/*")
                .contentType("application/x-www-form-urlencoded")
                .body("description=Measures+the+oxygen+saturation+%28SpO2%29+of+your+blood+on+demand.")
                .post(resolveLocation(location_productName__2, baseUrlOfSut + "/products/hrjF/features/6eeIC"))
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/description'] Instance type (null) does not match any allowed primitive type (allowed: ["string"])
        given().accept("application/json")
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .put(baseUrlOfSut + "/products/hrjF/features/6eeIC")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("6eeIC"))
                .body("'description'", nullValue());
        
        // Cleanup actions
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/hrjF")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
        given().accept("*/*")
                .delete(resolveLocation(location_productName__2, baseUrlOfSut + "/products/hrjF/features/6eeIC"))
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/hrjF/features/6eeIC")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) PUT:/products/{productName}/features/{featureName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 3 examples:
    *   (-) BODY -> RGB backlit keyboard with customizable zones and per-key lighting.
    *   (-) PATH: featureName -> backlit-keyboard
    *   (-) PATH: productName -> AeroBook-Pro-15
    */
    @Test(timeout = 60000)
    public void test_17_putOnFeaturShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .contentType("application/x-www-form-urlencoded")
                .body("description=RGB+backlit+keyboard+with+customizable+zones+and+per-key+lighting.")
                .put(baseUrlOfSut + "/products/AeroBook-Pro-15/features/backlit-keyboard")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/products/{productName}/configurations/{configurationName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 2 examples:
    *   (-) PATH: configurationName -> production-us-east
    *   (-) PATH: productName -> nexus-dashboard
    */
    @Test(timeout = 60000)
    public void test_18_deleteOnConfigurShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/nexus-dashboard/configurations/production-us-east")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (201) POST:/products/{productName}
    * 2 - (201) POST:/products/{productName}/configurations/{configurationName}
    * 3 - (204) DELETE:/products/{productName}/configurations/{configurationName}
    * Found 2 potential faults of type-code 101
    */
    @Test(timeout = 60000)
    public void test_19_deleteOnConfigurReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        ValidatableResponse res_0 = given().accept("*/*")
                .post(baseUrlOfSut + "/products/1fXQz9gHzdtLR")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        String location_productName__2 = res_0.extract().header("location");
        assertTrue(isValidURIorEmpty(location_productName__2));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}/configurations/{configurationName}' defines a response schema but no response body found.
        given().accept("*/*")
                .post(resolveLocation(location_productName__2, baseUrlOfSut + "/products/1fXQz9gHzdtLR/configurations/8Tq0t5HLkIDRo"))
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/1fXQz9gHzdtLR/configurations/8Tq0t5HLkIDRo")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Cleanup actions
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/1fXQz9gHzdtLR")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
        given().accept("*/*")
                .delete(resolveLocation(location_productName__2, baseUrlOfSut + "/products/1fXQz9gHzdtLR/configurations/8Tq0t5HLkIDRo"))
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/products/{productName}/features/{featureName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 1 example:
    *   (-) PATH: productName -> SmartWatch-Pro
    */
    @Test(timeout = 60000)
    public void test_20_deleteOnFeaturShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/SmartWatch-Pro/features/36T")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (201) POST:/products/{productName}
    * 2 - (201) POST:/products/{productName}/features/{featureName}
    * 3 - (204) DELETE:/products/{productName}/features/{featureName}
    * Found 3 potential faults of type-code 101
    * Using 1 example:
    *   (-) BODY -> Measures the oxygen saturation (SpO2) of your blood on demand.
    */
    @Test(timeout = 60000)
    public void test_21_deleteOnFeaturReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        ValidatableResponse res_0 = given().accept("*/*")
                .post(baseUrlOfSut + "/products/R")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        String location_productName__2 = res_0.extract().header("location");
        assertTrue(isValidURIorEmpty(location_productName__2));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}/features/{featureName}' defines a response schema but no response body found.
        given().accept("*/*")
                .contentType("application/x-www-form-urlencoded")
                .body("description=Measures+the+oxygen+saturation+%28SpO2%29+of+your+blood+on+demand.")
                .post(resolveLocation(location_productName__2, baseUrlOfSut + "/products/R/features/c0aoqZd7jQYqx_"))
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. DELETE on path '/products/{productName}/features/{featureName}' defines a response schema but no response body found.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/R/features/c0aoqZd7jQYqx_")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Cleanup actions
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/R")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
        given().accept("*/*")
                .delete(resolveLocation(location_productName__2, baseUrlOfSut + "/products/R/features/c0aoqZd7jQYqx_"))
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/products/{productName}/features/{featureName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 1 example:
    *   (-) PATH: featureName -> heart-rate-monitor
    */
    @Test(timeout = 60000)
    public void test_22_deleteOnFeaturShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/JtSBnK6GXMo/features/heart-rate-monitor")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (204) GET:/products/{productName}/configurations/{configurationName}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: productName -> MobileApp-Backend
    */
    @Test(timeout = 60000)
    public void test_23_getOnConfigurReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 204 not defined for path '/products/{productName}/configurations/{configurationName}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/products/MobileApp-Backend/configurations/4jRW")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/products/{productName}/configurations/{configurationName}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: configurationName -> production-us-east-1
    */
    @Test(timeout = 60000)
    public void test_24_getOnConfigurReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 204 not defined for path '/products/{productName}/configurations/{configurationName}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/products/p9h1upGF4/configurations/production-us-east-1")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) DELETE:/products/{productName}/constraints/{constraintId}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: productName -> UltraPhoneX
    */
    @Test(timeout = 60000)
    public void test_25_deleteOnConstraintReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. DELETE on path '/products/{productName}/constraints/{constraintId}' defines a response schema but no response body found.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/UltraPhoneX/constraints/225")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) DELETE:/products/{productName}/constraints/{constraintId}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: constraintId -> 12345
    */
    @Test(timeout = 60000)
    public void test_26_deleteOnConstraintReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. DELETE on path '/products/{productName}/constraints/{constraintId}' defines a response schema but no response body found.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/DA3yF3JCSkdgf/constraints/12345")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) DELETE:/products/{productName}/constraints/{constraintId}
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_27_deleteOnConstraintReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. DELETE on path '/products/{productName}/constraints/{constraintId}' defines a response schema but no response body found.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/aBJdG/constraints/-954890938")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) GET:/products/{productName}/configurations/{configurationName}/features
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 2 examples:
    *   (-) PATH: configurationName -> us-standard-16gb
    *   (-) PATH: productName -> ultra-laptop-x1
    */
    @Test(timeout = 60000)
    public void test_28_getOnConfigurFeaturesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .get(baseUrlOfSut + "/products/ultra-laptop-x1/configurations/us-standard-16gb/features")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (201) POST:/products/{productName}
    * 2 - (201) POST:/products/{productName}/configurations/{configurationName}
    * 3 - (200) GET:/products/{productName}/configurations/{configurationName}/features
    * Found 2 potential faults of type-code 101
    * Using 3 examples:
    *   (-) PATH: configurationName -> production-us-east
    *   (-) PATH: configurationName -> us-standard-16gb
    *   (-) PATH: configurationName -> us-standard-wifi
    */
    @Test(timeout = 60000)
    public void test_29_getOnConfigurFeaturesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}' defines a response schema but no response body found.
        ValidatableResponse res_0 = given().accept("*/*")
                .post(baseUrlOfSut + "/products/4OCJYyn87RbTj")
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        String location_productName__2 = res_0.extract().header("location");
        assertTrue(isValidURIorEmpty(location_productName__2));
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. POST on path '/products/{productName}/configurations/{configurationName}' defines a response schema but no response body found.
        ValidatableResponse res_1 = given().accept("*/*")
                .post(resolveLocation(location_productName__2, baseUrlOfSut + "/products/4OCJYyn87RbTj/configurations/us-standard-wifi"))
                .then()
                .statusCode(201)
                .assertThat()
                .body(isEmptyOrNullString());
        String location_configurationName__9 = res_1.extract().header("location");
        assertTrue(isValidURIorEmpty(location_configurationName__9));
        
        given().accept("application/json")
                .get(resolveLocation(location_configurationName__9, baseUrlOfSut + "/products/4OCJYyn87RbTj/configurations/us-standard-16gb/features"))
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
        
        // Cleanup actions
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/4OCJYyn87RbTj")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
        given().accept("*/*")
                .delete(resolveLocation(location_productName__2, baseUrlOfSut + "/products/4OCJYyn87RbTj/configurations/production-us-east"))
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) POST:/products/{productName}/configurations/{configurationName}/features/{featureName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 3 examples:
    *   (-) PATH: configurationName -> standard-gpu-cluster
    *   (-) PATH: featureName -> distributed-training
    *   (-) PATH: productName -> QuantumLeap-AI-Platform
    */
    @Test(timeout = 60000)
    public void test_30_postOnConfigurFeaturShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .post(baseUrlOfSut + "/products/QuantumLeap-AI-Platform/configurations/standard-gpu-cluster/features/distributed-training")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/products/{productName}/configurations/{configurationName}/features/{featureName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 2 examples:
    *   (-) PATH: featureName -> Realtime-Analytics-Dashboard
    *   (-) PATH: productName -> QuantumLeap-AI
    */
    @Test(timeout = 60000)
    public void test_31_deleteOnFeaturShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/QuantumLeap-AI/configurations/MzRaOmm/features/Realtime-Analytics-Dashboard")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/products/{productName}/configurations/{configurationName}/features/{featureName}
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 2 examples:
    *   (-) PATH: configurationName -> Premium-Tier
    *   (-) PATH: featureName -> Realtime-Analytics-Dashboard
    */
    @Test(timeout = 60000)
    public void test_32_deleteOnFeaturShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed. Response Content-Type header 'text/html;charset=utf-8' does not match any allowed types. Must be one of: [application/json].
        given().accept("*/*")
                .delete(baseUrlOfSut + "/products/S/configurations/Premium-Tier/features/Realtime-Analytics-Dashboard")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/html");
    }


}
