/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-07-06T20:52:02.782738890-03:00[America/Araguaina]
 * <br>
*  The generated test suite contains 8 tests
 * <br>
*  Covered targets: 23
 * <br>
*  Used time: 1h 0m 0s
 * <br>
*  Needed budget for current results: 0%
 * <br>
*  
*/
public class EvoMaster_Test {

    
    private static String baseUrlOfSut = "http://localhost:8080/actuator";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) QUERY: name -> John Smith
    */
    @Test(timeout = 60000)
    public void test_0_getOnRootReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. Instance type (object) does not match any allowed primitive type (allowed: ["string"])
        given().accept("*/*")
                .get(baseUrlOfSut + "/?name=John+Smith")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/vnd.spring-boot.actuator.v3+json")
                .body("'_links'.'beans'.'templated'", equalTo(false))
                .body("'_links'.'caches-cache'.'templated'", equalTo(true))
                .body("'_links'.'caches'.'templated'", equalTo(false))
                .body("'_links'.'health-path'.'templated'", equalTo(true))
                .body("'_links'.'health'.'templated'", equalTo(false))
                .body("'_links'.'info'.'templated'", equalTo(false))
                .body("'_links'.'conditions'.'templated'", equalTo(false))
                .body("'_links'.'shutdown'.'templated'", equalTo(false))
                .body("'_links'.'configprops'.'templated'", equalTo(false))
                .body("'_links'.'env'.'templated'", equalTo(false))
                .body("'_links'.'env-toMatch'.'templated'", equalTo(true))
                .body("'_links'.'logfile'.'templated'", equalTo(false))
                .body("'_links'.'loggers'.'templated'", equalTo(false))
                .body("'_links'.'loggers-name'.'templated'", equalTo(true))
                .body("'_links'.'heapdump'.'templated'", equalTo(false))
                .body("'_links'.'threaddump'.'templated'", equalTo(false))
                .body("'_links'.'prometheus'.'templated'", equalTo(false))
                .body("'_links'.'metrics-requiredMetricName'.'templated'", equalTo(true))
                .body("'_links'.'metrics'.'templated'", equalTo(false))
                .body("'_links'.'scheduledtasks'.'templated'", equalTo(false))
                .body("'_links'.'mappings'.'templated'", equalTo(false));
    }
    
    
    /**
    * Calls:
    * (200) GET:/
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_1_getOnRootReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. Instance type (object) does not match any allowed primitive type (allowed: ["string"])
        given().accept("*/*")
                .get(baseUrlOfSut + "/")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/vnd.spring-boot.actuator.v3+json")
                .body("'_links'.'beans'.'templated'", equalTo(false))
                .body("'_links'.'caches-cache'.'templated'", equalTo(true))
                .body("'_links'.'caches'.'templated'", equalTo(false))
                .body("'_links'.'health-path'.'templated'", equalTo(true))
                .body("'_links'.'health'.'templated'", equalTo(false))
                .body("'_links'.'info'.'templated'", equalTo(false))
                .body("'_links'.'conditions'.'templated'", equalTo(false))
                .body("'_links'.'shutdown'.'templated'", equalTo(false))
                .body("'_links'.'configprops'.'templated'", equalTo(false))
                .body("'_links'.'env'.'templated'", equalTo(false))
                .body("'_links'.'env-toMatch'.'templated'", equalTo(true))
                .body("'_links'.'logfile'.'templated'", equalTo(false))
                .body("'_links'.'loggers'.'templated'", equalTo(false))
                .body("'_links'.'loggers-name'.'templated'", equalTo(true))
                .body("'_links'.'heapdump'.'templated'", equalTo(false))
                .body("'_links'.'threaddump'.'templated'", equalTo(false))
                .body("'_links'.'prometheus'.'templated'", equalTo(false))
                .body("'_links'.'metrics-requiredMetricName'.'templated'", equalTo(true))
                .body("'_links'.'metrics'.'templated'", equalTo(false))
                .body("'_links'.'scheduledtasks'.'templated'", equalTo(false))
                .body("'_links'.'mappings'.'templated'", equalTo(false));
    }
    
    
    /**
    * Calls:
    * (200) GET:/
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_2_getOnRootReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. Instance type (object) does not match any allowed primitive type (allowed: ["string"])
        given().accept("*/*")
                .get(baseUrlOfSut + "/?name=Guest")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/vnd.spring-boot.actuator.v3+json")
                .body("'_links'.'beans'.'templated'", equalTo(false))
                .body("'_links'.'caches-cache'.'templated'", equalTo(true))
                .body("'_links'.'caches'.'templated'", equalTo(false))
                .body("'_links'.'health-path'.'templated'", equalTo(true))
                .body("'_links'.'health'.'templated'", equalTo(false))
                .body("'_links'.'info'.'templated'", equalTo(false))
                .body("'_links'.'conditions'.'templated'", equalTo(false))
                .body("'_links'.'shutdown'.'templated'", equalTo(false))
                .body("'_links'.'configprops'.'templated'", equalTo(false))
                .body("'_links'.'env'.'templated'", equalTo(false))
                .body("'_links'.'env-toMatch'.'templated'", equalTo(true))
                .body("'_links'.'logfile'.'templated'", equalTo(false))
                .body("'_links'.'loggers'.'templated'", equalTo(false))
                .body("'_links'.'loggers-name'.'templated'", equalTo(true))
                .body("'_links'.'heapdump'.'templated'", equalTo(false))
                .body("'_links'.'threaddump'.'templated'", equalTo(false))
                .body("'_links'.'prometheus'.'templated'", equalTo(false))
                .body("'_links'.'metrics-requiredMetricName'.'templated'", equalTo(true))
                .body("'_links'.'metrics'.'templated'", equalTo(false))
                .body("'_links'.'scheduledtasks'.'templated'", equalTo(false))
                .body("'_links'.'mappings'.'templated'", equalTo(false));
    }
    
    
    /**
    * Calls:
    * (401) GET:/slowApi
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) QUERY: delay -> 1000
    */
    @Test(timeout = 60000)
    public void test_3_getOnSlowApiReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/slowApi'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/slowApi?delay=1000")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401.0))
                .body("'error'", containsString("Unauthorized"))
                .body("'message'", containsString("Unauthorized"))
                .body("'path'", containsString("/actuator/slowApi"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/slowApi
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_4_getOnSlowApiReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/slowApi'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/slowApi")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401.0))
                .body("'error'", containsString("Unauthorized"))
                .body("'message'", containsString("Unauthorized"))
                .body("'path'", containsString("/actuator/slowApi"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/slowApi
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_5_getOnSlowApiReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/slowApi'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/slowApi?delay=242")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401.0))
                .body("'error'", containsString("Unauthorized"))
                .body("'message'", containsString("Unauthorized"))
                .body("'path'", containsString("/actuator/slowApi"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/slowApi
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_6_getOnSlowApiReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/slowApi'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/slowApi?delay=0")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401.0))
                .body("'error'", containsString("Unauthorized"))
                .body("'message'", containsString("Unauthorized"))
                .body("'path'", containsString("/actuator/slowApi"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/slowApi
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_7_getOnSlowApiWithQueryParamNegativeDelayReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/slowApi'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/slowApi?delay=-2045753248")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401.0))
                .body("'error'", containsString("Unauthorized"))
                .body("'message'", containsString("Unauthorized"))
                .body("'path'", containsString("/actuator/slowApi"));
    }


}
