/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-06T09:00:35.123288044-03:00[America/Araguaina]
 * <br>
*  The generated test suite contains 30 tests
 * <br>
*  Covered targets: 120
 * <br>
*  Used time: 1h 0m 0s
 * <br>
*  Needed budget for current results: 0%
 * <br>
*  
*/
public class EvoMaster_Test {

    
    private static String baseUrlOfSut = "http://localhost:8080";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/api/remainder/{a}/{b}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: a -> 17
    *   (-) PATH: b -> 5
    */
    @Test(timeout = 60000)
    public void test_0_getOnRemaindReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/remainder/17/5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(2.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/remainder/{a}/{b}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: b -> 5
    */
    @Test(timeout = 60000)
    public void test_1_getOnRemaindReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/remainder/306/5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(1.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/remainder/{a}/{b}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: a -> 17
    */
    @Test(timeout = 60000)
    public void test_2_getOnRemaindReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/remainder/17/527")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(-1.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/gammq/{a}/{x}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: a -> 5.5
    *   (-) PATH: x -> 2.3
    */
    @Test(timeout = 60000)
    public void test_3_getOnGammqReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/gammq/5.5/2.3")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.9489824333687313));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/gammq/{a}/{x}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: x -> 2.3
    */
    @Test(timeout = 60000)
    public void test_4_getOnGammqReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/gammq/0.9974166846191774/2.3")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.09981013106729382));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/gammq/{a}/{x}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: a -> 5.5
    */
    @Test(timeout = 60000)
    public void test_5_getOnGammqReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/gammq/5.5/0.46528585183105764")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.9999650784574511));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/expint/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: n -> 3
    *   (-) PATH: x -> 2.5
    */
    @Test(timeout = 60000)
    public void test_6_getOnExpintReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/expint/3/2.5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.016295368588209777));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/expint/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: x -> 2.5
    */
    @Test(timeout = 60000)
    public void test_7_getOnExpintReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/expint/881/2.5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(9.301386382792182E-5));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/bessj/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: n -> 3
    *   (-) PATH: x -> 2.5
    */
    @Test(timeout = 60000)
    public void test_8_getOnBessjReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/bessj/3/2.5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.21660039114156904));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/bessj/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: x -> 2.5
    */
    @Test(timeout = 60000)
    public void test_9_getOnBessjReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/bessj/186/2.5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/bessj/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: n -> 3
    */
    @Test(timeout = 60000)
    public void test_10_getOnBessjReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/bessj/3/0.21128193798017092")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(1.9594485138959517E-4));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/expint/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: n -> 3
    */
    @Test(timeout = 60000)
    public void test_11_getOnExpintReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/expint/3/0.7537879651181142")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.15394669995555235));
    }
    
    
    /**
    * Calls:
    * (400) GET:/api/bessj/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: x -> 2.5
    */
    @Test(timeout = 60000)
    public void test_12_getOnBessjReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. GET on path '/api/bessj/{n}/{x}' defines a response schema but no response body found.
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/bessj/-440932125/2.5")
                .then()
                .statusCode(400)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (400) GET:/api/expint/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: x -> 2.5
    */
    @Test(timeout = 60000)
    public void test_13_getOnExpintReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. GET on path '/api/expint/{n}/{x}' defines a response schema but no response body found.
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/expint/-1209514110/2.5")
                .then()
                .statusCode(400)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (400) GET:/api/remainder/{a}/{b}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: b -> 5
    */
    @Test(timeout = 60000)
    public void test_14_getOnRemaindReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. GET on path '/api/remainder/{a}/{b}' defines a response schema but no response body found.
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/remainder/-76470747/5")
                .then()
                .statusCode(400)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (400) GET:/api/remainder/{a}/{b}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: a -> 17
    */
    @Test(timeout = 60000)
    public void test_15_getOnRemaindReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. GET on path '/api/remainder/{a}/{b}' defines a response schema but no response body found.
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/remainder/17/-241070521")
                .then()
                .statusCode(400)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/triangle/{a}/{b}/{c}
    * Found 1 potential fault of type-code 101
    * Using 3 examples:
    *   (-) PATH: a -> 3
    *   (-) PATH: b -> 4
    *   (-) PATH: c -> 5
    */
    @Test(timeout = 60000)
    public void test_16_getOnTrianglReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/triangle/3/4/5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(1.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/triangle/{a}/{b}/{c}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: b -> 4
    *   (-) PATH: c -> 5
    */
    @Test(timeout = 60000)
    public void test_17_getOnTrianglReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/triangle/670/4/5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(0.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/triangle/{a}/{b}/{c}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: a -> 3
    *   (-) PATH: c -> 5
    */
    @Test(timeout = 60000)
    public void test_18_getOnTrianglReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/triangle/3/255/5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(0.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/triangle/{a}/{b}/{c}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: a -> 3
    *   (-) PATH: b -> 4
    */
    @Test(timeout = 60000)
    public void test_19_getOnTrianglReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/triangle/3/4/857")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(0.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/fisher/{m}/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 3 examples:
    *   (-) PATH: m -> 10
    *   (-) PATH: n -> 5
    *   (-) PATH: x -> 0.75
    */
    @Test(timeout = 60000)
    public void test_20_getOnFisherReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/fisher/10/5/0.75")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.3258593238499842));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/fisher/{m}/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: n -> 5
    *   (-) PATH: x -> 0.75
    */
    @Test(timeout = 60000)
    public void test_21_getOnFisherReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/fisher/65/5/0.75")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.2613727984072304));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/fisher/{m}/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: m -> 10
    *   (-) PATH: x -> 0.75
    */
    @Test(timeout = 60000)
    public void test_22_getOnFisherReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/fisher/10/484/0.75")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.32281932730503243));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/fisher/{m}/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: m -> 10
    *   (-) PATH: n -> 5
    */
    @Test(timeout = 60000)
    public void test_23_getOnFisherReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/fisher/10/5/0.4695393296238487")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.14463208715784276));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/triangle/{a}/{b}/{c}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: b -> 4
    *   (-) PATH: c -> 5
    */
    @Test(timeout = 60000)
    public void test_24_getOnTrianglReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/triangle/-1357505687/4/5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(0.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/triangle/{a}/{b}/{c}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: a -> 3
    *   (-) PATH: c -> 5
    */
    @Test(timeout = 60000)
    public void test_25_getOnTrianglReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/triangle/3/-1050705957/5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(0.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/fisher/{m}/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: m -> 10
    *   (-) PATH: x -> 0.75
    */
    @Test(timeout = 60000)
    public void test_26_getOnFisherReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsInt'] Instance type (null) does not match any allowed primitive type (allowed: ["integer"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/fisher/10/-1300531284/0.75")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", numberMatches(0.32245238505885493));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/fisher/{m}/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: n -> 5
    *   (-) PATH: x -> 0.75
    */
    @Test(timeout = 60000)
    public void test_27_getOnFisherReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (string) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/fisher/-806590040/5/0.75")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", nullValue())
                .body("'resultAsDouble'", containsString("NaN"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/triangle/{a}/{b}/{c}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: a -> 3
    *   (-) PATH: b -> 4
    */
    @Test(timeout = 60000)
    public void test_28_getOnTrianglReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type. [Path '/resultAsDouble'] Instance type (null) does not match any allowed primitive type (allowed: ["integer","number"])
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/triangle/3/4/-1290561167")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'resultAsInt'", numberMatches(0.0))
                .body("'resultAsDouble'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) GET:/api/fisher/{m}/{n}/{x}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: m -> 10
    *   (-) PATH: x -> 0.75
    */
    @Test(timeout = 60000)
    public void test_29_getOnFisherReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. GET on path '/api/fisher/{m}/{n}/{x}' defines a response schema but no response body found.
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/fisher/10/2038613830/0.75")
                .then()
                .statusCode(400)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
