/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-12T05:51:06.872568885-03:00[America/Araguaina]
 * <br>
*  The generated test suite contains 19 tests
 * <br>
*  Covered targets: 127
 * <br>
*  Used time: 1h 0m 0s
 * <br>
*  Needed budget for current results: 45%
 * <br>
*  
*/
public class EvoMaster_Test {

    
    private static String baseUrlOfSut = "http://localhost:8080";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/api/pat/{txt}
    * Using 1 example:
    *   (-) PATH: txt -> The quick brown fox jumps over the lazy dog.
    */
    @Test(timeout = 60000)
    public void test_0_getOnApiPatReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/pat/The%20quick%20brown%20fox%20jumps%20over%20the%20lazy%20dog.")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("none"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/title/{sex}/{title}
    * Using 2 examples:
    *   (-) PATH: sex -> male
    *   (-) PATH: title -> Smith
    */
    @Test(timeout = 60000)
    public void test_1_getOnTitlReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/title/male/Smith")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("-1"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/pat/{txt}/{pat}
    * Using 2 examples:
    *   (-) PATH: pat -> ABAB
    *   (-) PATH: txt -> ABABCABAB
    */
    @Test(timeout = 60000)
    public void test_2_getOnPatReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/pat/ABABCABAB/ABAB")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("1"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/notypevar/{i}/{s}
    * Using 2 examples:
    *   (-) PATH: i -> 5
    *   (-) PATH: s -> example-string
    */
    @Test(timeout = 60000)
    public void test_3_getOnNotypevarReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/notypevar/5/example-string")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/notypevar/{i}/{s}
    * Using 1 example:
    *   (-) PATH: s -> example-string
    */
    @Test(timeout = 60000)
    public void test_4_getOnNotypevarReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/notypevar/620/example-string")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("3"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/filesuffix/{directory}/{file}
    * Using 1 example:
    *   (-) PATH: file -> quarterly_report.docx
    */
    @Test(timeout = 60000)
    public void test_5_getOnFilesuffixReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/filesuffix/q1Iqzuu_4PGnfot/quarterly_report.docx")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/dateparse/{dayname}/{monthname}
    * Using 2 examples:
    *   (-) PATH: dayname -> Wednesday
    *   (-) PATH: monthname -> August
    */
    @Test(timeout = 60000)
    public void test_6_getOnDateparsReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/dateparse/Wednesday/August")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/costfuns/{i}/{s}
    * Using 2 examples:
    *   (-) PATH: i -> 1
    *   (-) PATH: s -> algorithm
    */
    @Test(timeout = 60000)
    public void test_7_getOnCostfunReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/costfuns/1/algorithm")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("10"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/costfuns/{i}/{s}
    * Using 1 example:
    *   (-) PATH: s -> algorithm
    */
    @Test(timeout = 60000)
    public void test_8_getOnCostfunReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/costfuns/585/algorithm")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("10"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/notypevar/{i}/{s}
    * Using 1 example:
    *   (-) PATH: s -> example-string
    */
    @Test(timeout = 60000)
    public void test_9_getOnNotypevarReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/notypevar/-131657029/example-string")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/costfuns/{i}/{s}
    * Using 1 example:
    *   (-) PATH: s -> algorithm
    */
    @Test(timeout = 60000)
    public void test_10_getOnCostfunReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/costfuns/-839154184/algorithm")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("10"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/api/filesuffix/{directory}/{file}
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) PATH: directory -> /home/user/documents
    *   (-) PATH: file -> quarterly_report.docx
    */
    @Test(timeout = 60000)
    public void test_11_getOnFilesuffixReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.request.path.missing. No API path found that matches request '/api/filesuffix//home/user/documents/quarterly_report.docx'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/api/filesuffix//home/user/documents/quarterly_report.docx")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(404.0))
                .body("'error'", containsString("Not Found"))
                .body("'message'", containsString("No message available"))
                .body("'path'", containsString("/api/filesuffix/home/user/documents/quarterly_report.docx"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/text2txt/{word1}/{word2}/{word3}
    * Found 1 potential fault of type-code 101
    * Using 3 examples:
    *   (-) PATH: word1 -> The
    *   (-) PATH: word2 -> quick
    *   (-) PATH: word3 -> brown
    */
    @Test(timeout = 60000)
    public void test_12_getOnText2txtReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing. GET on path '/api/text2txt/{word1}/{word2}/{word3}' defines a response schema but no response body found.
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/text2txt/The/quick/brown")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/cookie/{name}/{val}/{site}
    * Using 3 examples:
    *   (-) PATH: name -> session-id
    *   (-) PATH: site -> example.com
    *   (-) PATH: val -> abc-123-xyz-789
    */
    @Test(timeout = 60000)
    public void test_13_getOnCookiReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/cookie/session-id/abc-123-xyz-789/example.com")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/calc/{op}/{arg1}/{arg2}
    * Using 3 examples:
    *   (-) PATH: arg1 -> 15.5
    *   (-) PATH: arg2 -> 4.5
    *   (-) PATH: op -> add
    */
    @Test(timeout = 60000)
    public void test_14_getOnCalcReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/calc/add/15.5/4.5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("0.0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/calc/{op}/{arg1}/{arg2}
    * Using 2 examples:
    *   (-) PATH: arg2 -> 4.5
    *   (-) PATH: op -> add
    */
    @Test(timeout = 60000)
    public void test_15_getOnCalcReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/calc/add/0.3408981379987024/4.5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("0.0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/calc/{op}/{arg1}/{arg2}
    * Using 2 examples:
    *   (-) PATH: arg1 -> 15.5
    *   (-) PATH: op -> add
    */
    @Test(timeout = 60000)
    public void test_16_getOnCalcReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/calc/add/15.5/0.772201794473323")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("0.0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/text2txt/{word1}/{word2}/{word3}
    * Using 1 example:
    *   (-) PATH: word2 -> quick
    */
    @Test(timeout = 60000)
    public void test_17_getOnText2txtReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/text2txt/YOU/quick/7")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("u"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/api/ordered4/{w}/{x}/{z}/{y}
    * Using 4 examples:
    *   (-) PATH: w -> zebra
    *   (-) PATH: x -> yak
    *   (-) PATH: y -> wolf
    *   (-) PATH: z -> x-ray
    */
    @Test(timeout = 60000)
    public void test_18_getOnOrdered4ReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/ordered4/zebra/yak/x-ray/wolf")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("unordered"));
    }


}
